<?php

use App\Utilities\Prefecture;

class PrefectureTest extends TestCase
{
    /** @var Prefecture */
    private $prefecture;

    /**
     *
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->prefecture = new Prefecture();
    }

    /**
     * @dataProvider provideToIdParams
     * @param string $pref
     * @param bool $hasSuffix
     * @param int $expected
     */
    public function testToId(string $pref, bool $hasSuffix, int $expected)
    {
        $this->assertEquals($expected, $this->prefecture->toId($pref, $hasSuffix));
    }

    /**
     * @dataProvider provideToIdIllegalParams
     * @expectedException InvalidArgumentException
     * @param string $pref
     * @param bool $hasSuffix
     */
    public function testConvertFailed(string $pref, bool $hasSuffix)
    {
        $this->prefecture->toId($pref, $hasSuffix);
    }

    /**
     * @return array
     */
    public function provideToIdParams()
    {
        return [
            ['北海道', true, 1],
            ['青森県', true, 2],
            ['東京都', true, 13],
            ['大阪府', true, 27],
            ['北海道', false, 1],
            ['青森', false, 2],
            ['東京', false, 13],
            ['大阪', false, 27],
        ];
    }

    /**
     * @return array
     */
    public function provideToIdIllegalParams()
    {
        return [
            ['不正な値', true, 1],
            ['東京', true, 13],
            ['北海', false, 1],
            ['青森県', false, 2],
        ];
    }

    /**
     * @dataProvider provideToStringParams
     * @param int $id
     * @param string $expected
     */
    public function testToString(int $id, string $expected)
    {
        $this->assertEquals($expected, $this->prefecture->toString($id));
    }

    /**
     * @dataProvider provideToStringIllegalParams
     * @expectedException InvalidArgumentException
     * @param int $id
     */
    public function testToStringFailed(int $id)
    {
        $this->prefecture->toString($id);
    }

    /**
     * @return array
     */
    public function provideToStringParams()
    {
        return [
            [1, '北海道'],
            [2, '青森県'],
        ];
    }

    /**
     * @return array
     */
    public function provideToStringIllegalParams()
    {
        return [
            [0], [48]
        ];
    }
}